// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCciV0k6opWU1Kjo04GSmyuTOQlTvsJqS4',
    appId: '1:487800877880:web:12a2bcf76b8a3a7e05c7cd',
    messagingSenderId: '487800877880',
    projectId: 'tiktok-clone-app-daf34',
    authDomain: 'tiktok-clone-app-daf34.firebaseapp.com',
    storageBucket: 'tiktok-clone-app-daf34.appspot.com',
    measurementId: 'G-EYLTT0YKLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu1r7gnilvOgAhIi5taALjII9qZwZb4Cw',
    appId: '1:487800877880:android:ef1ff6731070599605c7cd',
    messagingSenderId: '487800877880',
    projectId: 'tiktok-clone-app-daf34',
    storageBucket: 'tiktok-clone-app-daf34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwoDTW-MQOV74DwmWcbLynPCYiUzQpf78',
    appId: '1:487800877880:ios:13ce8c9efa5dfebb05c7cd',
    messagingSenderId: '487800877880',
    projectId: 'tiktok-clone-app-daf34',
    storageBucket: 'tiktok-clone-app-daf34.appspot.com',
    iosBundleId: 'com.example.vidstarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwoDTW-MQOV74DwmWcbLynPCYiUzQpf78',
    appId: '1:487800877880:ios:13ce8c9efa5dfebb05c7cd',
    messagingSenderId: '487800877880',
    projectId: 'tiktok-clone-app-daf34',
    storageBucket: 'tiktok-clone-app-daf34.appspot.com',
    iosBundleId: 'com.example.vidstarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCciV0k6opWU1Kjo04GSmyuTOQlTvsJqS4',
    appId: '1:487800877880:web:4300aaedb1e72e6c05c7cd',
    messagingSenderId: '487800877880',
    projectId: 'tiktok-clone-app-daf34',
    authDomain: 'tiktok-clone-app-daf34.firebaseapp.com',
    storageBucket: 'tiktok-clone-app-daf34.appspot.com',
    measurementId: 'G-2JW12WGTV8',
  );
}
